### ISSUE TITLE
Compilers unrecognised on Windows

### ISSUE THREAD

**Issue by TysonRayJones** [mpi4py/setup-mpi#9]
Hi there,

Thanks very much for a wonderfully helpful Github Action!

I was wondering what the compiler command is when on Windows. I've tried
```bash
mpicc
mpic++
mpicxx
```
but none of them are recognised, though they work on `ubuntu-latest` and `macos-latest`. 

My workflow is a very simple:
```yml
jobs:

  cpp_mpi:
    name: C++ (MPI)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: mpi4py/setup-mpi@v1

      - name: compile backend
        run: |
          mpicxx -c mycode.cpp
```
but my [actions](https://github.com/TysonRayJones/InteroperableComplex/actions/runs/7758649593/job/21160916619) report that `mpicxx` is not recognised.

I can see in the [CI](https://github.com/mpi4py/setup-mpi/blob/40c19a60792debf8ca403a3e6ee5f84c4e76555d/.github/workflows/ci.yml#L100) that these commands should work, at least when using the Intel MPI compiler.

What am I doing wrong? Do I need to give the action extra clues about my os?
